import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { ControlPlane, ControlPlaneError, TASK_STATUS } from '../runtime/control-plane.mjs';

function fixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'opencode-system-')); return { root, plane: new ControlPlane(root) }; }
test('executes a dependency-aware task graph with evidence gates', () => { const { plane } = fixture(); plane.initialize({ goal: 'Ship a feature' }); plane.addTask({ id: 'design', title: 'Design', requiredEvidence: ['review'] }); plane.addTask({ id: 'build', title: 'Build', dependencies: ['design'], requiredEvidence: ['test'] }); assert.deepEqual(plane.readyTasks().map((task) => task.id), ['design']); plane.startTask('design'); assert.throws(() => plane.completeTask('design'), (error) => error.code === 'EVIDENCE_REQUIRED'); plane.recordEvidence('design', { type: 'review', summary: 'Plan approved' }); plane.completeTask('design'); assert.deepEqual(plane.readyTasks().map((task) => task.id), ['build']); plane.startTask('build'); plane.recordEvidence('build', { type: 'test', summary: 'tests pass' }); plane.completeTask('build'); assert.equal(plane.status().status, 'COMPLETE'); });
test('persists failures and bounds retries', () => { const { plane } = fixture(); plane.initialize({ goal: 'Fix a bug', budgets: { retriesPerTask: 2 } }); plane.addTask({ id: 'fix', title: 'Fix', requiredEvidence: [] }); plane.startTask('fix'); assert.equal(plane.failTask('fix', { category: 'TEST', cause: 'red' }).task.status, TASK_STATUS.PENDING); plane.startTask('fix'); assert.equal(plane.failTask('fix', { category: 'TEST', cause: 'still red' }).task.status, TASK_STATUS.FAILED); assert.equal(plane.load().failures.length, 2); assert.equal(plane.status().status, 'BLOCKED'); });
test('rejects unknown dependencies and cycles', () => { const { plane } = fixture(); plane.initialize({ goal: 'Validate DAG' }); assert.throws(() => plane.addTask({ id: 'a', title: 'A', dependencies: ['missing'] }), (error) => error instanceof ControlPlaneError && error.code === 'UNKNOWN_DEPENDENCY'); plane.addTask({ id: 'a', title: 'A' }); plane.addTask({ id: 'b', title: 'B', dependencies: ['a'] }); const state = plane.load(); state.tasks.a.dependencies = ['b']; fs.writeFileSync(path.join(plane.dir, 'state.json'), JSON.stringify(state)); assert.throws(() => plane.load(), (error) => error.code === 'TASK_CYCLE'); });

// ─── WorkerAdapter tests ──────────────────────────────────────────────

import { WorkerAdapter } from '../runtime/worker.mjs';

test('WorkerAdapter executes a shell task and records evidence', async () => { const { root, plane } = fixture(); plane.initialize({ goal: 'Test worker' }); plane.addTask({ id: 'echo', title: 'Echo test', kind: 'shell', command: 'echo hello', requiredEvidence: ['test'] }); const worker = new WorkerAdapter(plane); const result = await worker.execute('echo'); assert.equal(result.success, true); assert.equal(result.evidence.length, 1); assert.equal(result.evidence[0].type, 'test'); assert.equal(result.evidence[0].verdict, 'PASS'); const state = plane.load(); assert.equal(state.tasks.echo.status, 'COMPLETE'); assert.equal(state.evidence.length, 1); });

test('WorkerAdapter handles failing shell command', async () => { const { plane } = fixture(); plane.initialize({ goal: 'Test worker fail' }); plane.addTask({ id: 'fail', title: 'Fail test', kind: 'shell', command: 'exit 1', requiredEvidence: [] }); const worker = new WorkerAdapter(plane); const result = await worker.execute('fail'); assert.equal(result.success, false); assert.ok(result.error); const state = plane.load(); assert.equal(state.tasks.fail.status, 'PENDING'); assert.equal(state.failures.length, 1); assert.equal(state.failures[0].category, 'UNKNOWN'); });

test('WorkerAdapter classifies timeout errors', async () => { const { plane } = fixture(); plane.initialize({ goal: 'Test timeout' }); plane.addTask({ id: 'slow', title: 'Slow task', kind: 'shell', command: 'ping -n 30 127.0.0.1', requiredEvidence: [] }); const worker = new WorkerAdapter(plane, { timeout: 500 }); const result = await worker.execute('slow'); assert.equal(result.success, false); assert.equal(result.category, 'TIMEOUT'); });

test('WorkerAdapter executes a file task', async () => { const { plane, root } = fixture(); plane.initialize({ goal: 'Test file task' }); plane.addTask({ id: 'write', title: 'Write file', kind: 'file', path: 'output.txt', content: 'hello world', requiredEvidence: ['build'] }); const worker = new WorkerAdapter(plane); const result = await worker.execute('write'); assert.equal(result.success, true); assert.ok(fs.existsSync(path.join(root, 'output.txt'))); assert.equal(fs.readFileSync(path.join(root, 'output.txt'), 'utf8'), 'hello world'); });

test('WorkerAdapter preview runs without modifying state', async () => { const { plane } = fixture(); plane.initialize({ goal: 'Test preview' }); plane.addTask({ id: 't1', title: 'Task 1', kind: 'shell', command: 'echo preview', requiredEvidence: [] }); const worker = new WorkerAdapter(plane); const result = await worker.preview({ kind: 'shell', command: 'echo preview' }, plane.projectRoot); assert.ok(result); const state = plane.load(); assert.equal(state.tasks.t1.status, 'PENDING'); });

// ─── Scheduler tests ──────────────────────────────────────────────────

import { Scheduler } from '../runtime/scheduler.mjs';

test('Scheduler executes ready tasks and stops at idle', async () => { const { plane } = fixture(); plane.initialize({ goal: 'Test scheduler' }); plane.addTask({ id: 't1', title: 'Task 1', kind: 'shell', command: 'echo one', requiredEvidence: ['test'] }); plane.addTask({ id: 't2', title: 'Task 2', kind: 'shell', command: 'echo two', dependencies: ['t1'], requiredEvidence: ['test'] }); const scheduler = new Scheduler(plane, { stopOnFail: false }); const summary = await scheduler.run(); assert.equal(summary.succeeded, 2); assert.equal(summary.failed, 0); assert.equal(summary.iterations, 2); assert.equal(plane.status().status, 'COMPLETE'); });

test('Scheduler stops on failure when stopOnFail=true', async () => { const { plane } = fixture(); plane.initialize({ goal: 'Test stop on fail', budgets: { retriesPerTask: 1 } }); plane.addTask({ id: 'ok', title: 'OK task', kind: 'shell', command: 'echo ok', requiredEvidence: ['test'] }); plane.addTask({ id: 'bad', title: 'Bad task', kind: 'shell', command: 'exit 1', dependencies: ['ok'], requiredEvidence: [] }); const scheduler = new Scheduler(plane, { stopOnFail: true }); const summary = await scheduler.run(); assert.equal(summary.succeeded, 1); assert.equal(summary.failed, 1); assert.equal(plane.status().status, 'BLOCKED'); });

test('Scheduler step executes one task', async () => { const { plane } = fixture(); plane.initialize({ goal: 'Test step' }); plane.addTask({ id: 'a', title: 'A', kind: 'shell', command: 'echo a', requiredEvidence: ['test'] }); plane.addTask({ id: 'b', title: 'B', kind: 'shell', command: 'echo b', requiredEvidence: ['test'] }); const scheduler = new Scheduler(plane); const step1 = await scheduler.step(); assert.equal(step1.executed.success, true); assert.equal(step1.executed.taskId, 'a'); const step2 = await scheduler.step(); assert.equal(step2.executed.taskId, 'b'); const step3 = await scheduler.step(); assert.equal(step3.executed, null); });

test('Scheduler respects maxIterations budget', async () => { const { plane } = fixture(); plane.initialize({ goal: 'Test budget' }); for (let i = 0; i < 10; i++) { plane.addTask({ id: `t${i}`, title: `Task ${i}`, kind: 'shell', command: `echo ${i}`, requiredEvidence: ['test'] }); } const scheduler = new Scheduler(plane, { maxIterations: 3 }); const summary = await scheduler.run(); assert.equal(summary.iterations, 3); assert.equal(summary.succeeded, 3); });

test('Scheduler emits events', async () => { const { plane } = fixture(); plane.initialize({ goal: 'Test events' }); plane.addTask({ id: 'e1', title: 'E1', kind: 'shell', command: 'echo e1', requiredEvidence: ['test'] }); const scheduler = new Scheduler(plane); const events = []; scheduler.on('scheduler:start', (e) => events.push({ type: 'start', ...e })); scheduler.on('scheduler:dispatch', (e) => events.push({ type: 'dispatch', ...e })); scheduler.on('scheduler:result', (e) => events.push({ type: 'result', ...e })); scheduler.on('scheduler:done', (e) => events.push({ type: 'done', ...e })); await scheduler.run(); assert.ok(events.some((e) => e.type === 'start')); assert.ok(events.some((e) => e.type === 'dispatch')); assert.ok(events.some((e) => e.type === 'result')); assert.ok(events.some((e) => e.type === 'done')); });
